spring:
  h2:
    console:
      enabled: true
      path: '/console'
  jpa:
    hibernate:
      #      ddl-auto: validate
      ddl-auto: create-drop
  datasource:
    url: 'jdbc:h2:mem:peak-logistic'
  #    url: 'jdbc:h2:file:./peak-logistic'

  main:
    banner-mode: off
  flyway:
    baseline-on-migrate: true