spring:

  h2:
    console:
      enabled: true
      path: '/console'
  jpa:
    hibernate:
      #      ddl-auto: validate
      #      ddl-auto: create-drop
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: 'jdbc:h2:mem:peak-logistic'
    username: sa
    password: root
    driverClassName: org.h2.Driver

  #    url: 'jdbc:h2:file:./peak-logistic'

  main:
    banner-mode: off
  flyway:
    baseline-on-migrate: true